# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/changePosition_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 375)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("uiFiles\\../GUI/istockphoto-1013490744-1024x1024.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setHorizontalSpacing(25)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.lbl_FirstName = QtWidgets.QLabel(Dialog)
        self.lbl_FirstName.setObjectName("lbl_FirstName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_FirstName)
        self.lbl_FirstName_value = QtWidgets.QLabel(Dialog)
        self.lbl_FirstName_value.setObjectName("lbl_FirstName_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_FirstName_value)
        self.lbl_lastName = QtWidgets.QLabel(Dialog)
        self.lbl_lastName.setObjectName("lbl_lastName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_lastName)
        self.lbl_LastName_value = QtWidgets.QLabel(Dialog)
        self.lbl_LastName_value.setObjectName("lbl_LastName_value")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_LastName_value)
        self.lbl_currentPosition = QtWidgets.QLabel(Dialog)
        self.lbl_currentPosition.setObjectName("lbl_currentPosition")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_currentPosition)
        self.lbl_currentPosition_value = QtWidgets.QLabel(Dialog)
        self.lbl_currentPosition_value.setObjectName("lbl_currentPosition_value")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_currentPosition_value)
        self.lbl_newPosition = QtWidgets.QLabel(Dialog)
        self.lbl_newPosition.setObjectName("lbl_newPosition")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_newPosition)
        self.tf_newPosition = QtWidgets.QLineEdit(Dialog)
        self.tf_newPosition.setObjectName("tf_newPosition")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tf_newPosition)
        self.lbl_Reason = QtWidgets.QLabel(Dialog)
        self.lbl_Reason.setObjectName("lbl_Reason")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_Reason)
        self.tf_reason = QtWidgets.QLineEdit(Dialog)
        self.tf_reason.setObjectName("tf_reason")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tf_reason)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(122, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_FirstName.setText(_translate("Dialog", "First Name"))
        self.lbl_FirstName_value.setText(_translate("Dialog", "Tobias"))
        self.lbl_lastName.setText(_translate("Dialog", "Last Name"))
        self.lbl_LastName_value.setText(_translate("Dialog", "Spronk"))
        self.lbl_currentPosition.setText(_translate("Dialog", "Current Position"))
        self.lbl_currentPosition_value.setText(_translate("Dialog", "Engineer"))
        self.lbl_newPosition.setText(_translate("Dialog", "New Position"))
        self.lbl_Reason.setText(_translate("Dialog", "Reason"))
        self.tf_reason.setPlaceholderText(_translate("Dialog", "Optional"))
        self.pushButton.setText(_translate("Dialog", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
