# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiFiles/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(302, 409)
        MainWindow.setMinimumSize(QtCore.QSize(200, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("uiFiles\\../GUI/istockphoto-1013490744-1024x1024.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(200, 400))
        self.centralwidget.setMaximumSize(QtCore.QSize(400, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vboxlayout.setContentsMargins(-1, -1, 9, -1)
        self.vboxlayout.setSpacing(15)
        self.vboxlayout.setObjectName("vboxlayout")
        spacerItem = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.btn_manageEmployee = QtWidgets.QPushButton(self.centralwidget)
        self.btn_manageEmployee.setMinimumSize(QtCore.QSize(200, 60))
        self.btn_manageEmployee.setObjectName("btn_manageEmployee")
        self.vboxlayout.addWidget(self.btn_manageEmployee)
        self.btn_viewCharts = QtWidgets.QPushButton(self.centralwidget)
        self.btn_viewCharts.setMinimumSize(QtCore.QSize(200, 60))
        self.btn_viewCharts.setObjectName("btn_viewCharts")
        self.vboxlayout.addWidget(self.btn_viewCharts)
        spacerItem1 = QtWidgets.QSpacerItem(20, 110, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.vboxlayout.setStretch(0, 2)
        self.vboxlayout.setStretch(1, 1)
        self.vboxlayout.setStretch(2, 1)
        self.vboxlayout.setStretch(3, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_manageEmployee.setText(_translate("MainWindow", "Manage Employees"))
        self.btn_viewCharts.setText(_translate("MainWindow", "View Charts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
